# Nama workflow ini, akan muncul di tab Actions GitHub Anda
name: Preprocess Breast Cancer Data Workflow

# Memicu workflow ini setiap kali ada push ke branch 'main' (atau 'master')
# Anda bisa sesuaikan branch name sesuai branch utama repo Anda
on:
  push:
    branches:
      - main # Ganti 'main' jika branch utama Anda 'master' atau nama lain
  # Memungkinkan Anda menjalankan workflow secara manual dari GitHub Actions UI
  workflow_dispatch: 

# Jobs yang akan dijalankan dalam workflow ini
jobs:
  preprocess:
    # Menjalankan job di Ubuntu latest runner
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan dalam job ini
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Action untuk mengambil kode dari repositori

    - name: Set up Python
      uses: actions/setup-python@v5 # Action untuk setup Python
      with:
        python-version: '3.9' # Anda bisa ganti versi Python yang Anda inginkan, misalnya '3.10', '3.11'

    - name: Install Dependencies
      run: |
        # Asumsikan Anda tidak punya requirements.txt.
        # Jika Anda punya requirements.txt, gunakan: pip install -r requirements.txt
        # Pastikan semua library yang digunakan terinstal di sini
        pip install pandas numpy scikit-learn

    - name: Debug - List Files and Directories (for troubleshooting)
      # Ini akan mencetak struktur folder dan file di dalam runner.
      # Pastikan 'breast_cancer_dataset/data.csv' terlihat di sini.
      run: |
        echo "Listing contents of current directory (root of repository):"
        ls -l
        echo "Listing contents of breast_cancer_dataset/:"
        ls -l breast_cancer_dataset/
        echo "Listing contents of preprocessing/:"
        ls -l preprocessing/
        echo "Listing contents of preprocessing/breast_cancer_dataset_preprocessed/ (if it exists):"
        ls -l preprocessing/breast_cancer_dataset_preprocessed/ || echo "Folder does not exist yet or is empty."


    - name: Run Data Preprocessing Script
      run: |
        # Panggil script Python Anda dari folder preprocessing
        # Perhatikan path relatifnya dari root proyek
        python preprocessing/automate_Zulfahmi_M_Ardianto.py

    - name: Upload Preprocessed Data as Artifact
      # Ini adalah alternatif yang lebih aman daripada meng-commit data kembali ke repo.
      # Hasil preprocessing akan tersedia untuk diunduh sebagai artifact di job run.
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-data
        # Path ini harus sesuai dengan lokasi file output yang dibuat oleh script Python Anda
        path: |
          preprocessing/breast_cancer_dataset_preprocessed/X_train_scaled.csv
          preprocessing/breast_cancer_dataset_preprocessed/X_test_scaled.csv
          preprocessing/breast_cancer_dataset_preprocessed/y_train.csv
          preprocessing/breast_cancer_dataset_preprocessed/y_test.csv
        # Anda bisa mengatur berapa lama artifact akan disimpan (default 90 hari)
        # retention-days: 7
